### PR TITLE
Switch to src layout

### LINKED ISSUE #270: Switch to src layout
It might be possible that we are not testing the installed version of the package in our CI workflow. This is one of [the major disadvantages in using a flat layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/). Experimenting in a fork of benchcab shows that switching to src layout and not including the package data causes the CI to fail to find the data directory ([see logs](https://github.com/SeanBryan51/benchcab/actions/runs/8353949217/job/22866490538?pr=2)) which reproduces the error found in #267.

_Originally posted by @SeanBryan51 in https://github.com/CABLE-LSM/benchcab/issues/267#issuecomment-2008646884_

### PR DESCRIPTION
**Pull request by SeanBryan51**
Currently we are not testing the installed version of the package in our CI workflow. This is one of [the major disadvantages in using a flat layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/). This change switches the source code to use a src layout and reproduces the error described in https://github.com/CABLE-LSM/benchcab/issues/267 (see [logs](https://github.com/CABLE-LSM/benchcab/actions/runs/8354125740/job/22866966878)).

This pull request should be merged once #272 is merged so that we can verify the CI passes.

Fixes #270

### CODE REVIEW

**Comment by abhaasgoyal** [comment]
Wouldn't `src` clash with the current folders created by runs of `benchcab` (this could further be a problem when we run `benchcab clean`).

```
└── src
    ├── benchcab <- Work on this PR
    ├── <realisation-0>
    └── <realisation-1>
```
For example , running `benchcab clean` would delete `benchcab` as well. Also, I believe `src` is holding folders for 2 different things here.

**Comment by SeanBryan51** [comment]
@abhaasgoyal I think you might be confusing the benchcab source with [bench_example](https://github.com/CABLE-LSM/bench_example). The src directory you mentioned is only generated when running benchcab and will not contain the benchcab source files.

**Comment by abhaasgoyal** [comment]
Oh yeah, my mistake.. Looks good to me! (I ran the integration tests as well)

**Comment by SeanBryan51** [comment]
I've noticed the code coverage reports seem to differ when I have hardly changed the source code or the unit tests. Looking into this now.

**Comment by SeanBryan51** [comment]
@abhaasgoyal I've made some new changes regarding the unit test coverage reports as coverage reports do not seem to be properly generated unless we run pytest against an editable install of benchcab. I've also restricted the coverage to measure only the source files under the `src` directory as files like versioneer.py were getting picked up by the coverage report.

Also please hit approve once you are happy with the changes.

**Review by abhaasgoyal — APPROVED** [review]
LGTM

**Pull request merged**
