### PR TITLE
Replace dict of dicts with list of dicts

### LINKED ISSUE #57: `realisations` and `science_configurations` keys should be lists
The `realisations` and `science_configurations` keys should be lists instead of key value pairs in the config file. We should also support the ability for the user to specify $N \gt 0$ realisations.

### PR DESCRIPTION
**Pull request by SeanBryan51**
The `realisations` and `science_configurations` keys should be lists instead of key value pairs in the config file.

Add the ability for the user to specify $N > 0$ realisations in the config file.

Fixes #57

## Testing
- `pytest` success
- `pip install --user .` success
- `benchcab -f` success

### CODE REVIEW

**Comment by SeanBryan51** [comment]
I've resolved merge conflicts with the master branch and have re-ran the following commands:
- `pytest` success
- `pip install --user .` success
- `benchcab run` success

**Review by ccarouge — APPROVED** [review]
One question though: have you checked everything works if we run with 1 or 3 realisations?

**Comment by SeanBryan51** [comment]
Good catch, I have not run a full test with one or greater than two branches in the config, will do that now...

**Comment by SeanBryan51** [comment]
I have now ran `benchcab run` successfully using 1, 2 or 3 branches in the config file. This should be ok to merge.

**Comment by ccarouge** [comment]
Great, go and merge.

**Pull request merged**
